Debugging Issue with method not found when trying to run the Component Scanning test at section 2.2.2.1 was because I had not added the spring-context-support dependency, and also because my springframework dependencies were not all the same version https://www.technicalkeeda.com/spring-tutorials/java-lang-nosuchmethoderror-org-springframework-core-annotation-annotatedelementutils-findmergedannotation-ljava-lang-reflect-annotatedelement-ljava-lang-class-java-lang-annotation-annotation
Also, Created Java Configured Aspect for Minstrel class in knights package.